name: Anchore Syft SBOM scan

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  Anchore-Repo-Scan:
    permissions:
      contents: write # Required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    
    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    
    - name: Generate SBOM for the repository
      run: syft dir:. -o spdx-json=repo-sbom.spdx.json
    
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: repo-sbom
        path: repo-sbom.spdx.json

    - name: Upload to GitHub Dependency submission API
      uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
      with:
        artifact-name: repo-sbom.spdx.json
        dependency-snapshot: true
